### ISSUE TITLE
UsersWP - GetPaid - GeoDirectory - storing, managing, and displaying user meta

### ISSUE THREAD

**Issue by alexrollin** [UsersWP/userswp#405]
Use cases mentioned by our members

WooCommerce

- [ ] Import WooCommerce Customer Data into GetPaid
- [ ] Export GetPaid Customer Data - for use in WooCommerce

GeoDirectory

- [ ] Populate Invoice / checkout fields with data from UsersWP / GetPaid Customer Data and custom fields
- [ ] Populate listing custom fields with UsersWP / GetPaid custom field data
- [ ] Register a user and then use user data in checkout/invoice
- [ ] Create manual invoice for package and link to existing Published listing 
- [ ] See list of invoices associated with listing in backend listing edit screen
- [ ] 

UsersWP 

- [ ] Profile tab with company and address info(customer data) (standard pre-defined customer fields)
- [ ] ability to set any fields as required during registration, optional on profile
- [ ] Populate popular form fields with user meta like username, author ID, First Name and Last Name and UsersWP custom fields
       ex. GD Contact form could auto-populate with username first name and last name in hidden fields.
- [ ] Import users without triggering email
- [ ] Import users with options for passwords - like auto-generate, don't auto-generate

GetPaid

- [ ] Import customers and customer data
- [ ] Export customers and customer data
- [ ] Easily show Listing data on invoice
- [ ] Easily show profile meta on invoice
- [ ]  Force company and VAT or other field to be required  (similar field management)
- [ ] Add custom fields

Single Importer

- [ ] UWP already has an importer/exporter - can we keep the profile meta importers working together or make it an addon that works for uwp or GetPaid?
